"""initial

Revision ID: 22b3495f51b3
Revises: 3580f019795f
Create Date: 2023-03-22 17:16:37.399004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b3495f51b3'
down_revision = '3580f019795f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('photo_url', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id', 'price'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('cart',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('order', sa.String(length=60), nullable=True),
    sa.Column('order_value', sa.Integer(), nullable=True),
    sa.Column('order_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['products.name'], ),
    sa.ForeignKeyConstraint(['order_owner'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['order_value'], ['products.price'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
