"""initial

Revision ID: 41c3d6ed52d8
Revises: 64b0f7110c58
Create Date: 2023-03-22 17:23:45.520219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c3d6ed52d8'
down_revision = '64b0f7110c58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('photo_url', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('cart',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('order_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_owner'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
