"""initial

Revision ID: 4d3ba89ee98a
Revises: b17db570f188
Create Date: 2023-03-22 17:50:05.989678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3ba89ee98a'
down_revision = 'b17db570f188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
