"""empty message

Revision ID: 73179e1cf8af
Revises: dc137cd58b3d
Create Date: 2023-04-04 19:38:30.939264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73179e1cf8af'
down_revision = 'dc137cd58b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
