"""initial

Revision ID: 9925a48853bc
Revises: 41c3d6ed52d8
Create Date: 2023-03-22 17:25:49.054732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9925a48853bc'
down_revision = '41c3d6ed52d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('order', sa.String(length=60), nullable=True))
    op.add_column('cart', sa.Column('order_value', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'products', ['order'], ['name'])
    op.create_foreign_key(None, 'cart', 'products', ['order_value'], ['price'])
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'order_value')
    op.drop_column('cart', 'order')
    # ### end Alembic commands ###
