"""initial

Revision ID: 993dc640a259
Revises: bbef6b118570
Create Date: 2023-03-23 14:11:45.923142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993dc640a259'
down_revision = 'bbef6b118570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
