"""initial

Revision ID: 9e031a442fb0
Revises: 9925a48853bc
Create Date: 2023-03-22 17:44:56.578721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e031a442fb0'
down_revision = '9925a48853bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('order_value', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'products', ['order_value'], ['price'])
    op.create_foreign_key(None, 'cart', 'products', ['order'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'order_value')
    op.drop_column('cart', 'order')
    # ### end Alembic commands ###
