"""empty message

Revision ID: aee3d199b9f0
Revises: cea13224b63b
Create Date: 2023-03-26 00:51:45.489171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee3d199b9f0'
down_revision = 'cea13224b63b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
