"""initial

Revision ID: b17db570f188
Revises: 9e031a442fb0
Create Date: 2023-03-22 17:46:12.989768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17db570f188'
down_revision = '9e031a442fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('order_value', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'products', ['order'], ['Id'])
    op.create_foreign_key(None, 'cart', 'products', ['order_value'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'order_value')
    op.drop_column('cart', 'order')
    # ### end Alembic commands ###
